$('.material-filter').owlCarousel({
    loop:false,
    margin:5,
    nav:true,
    rtl:true,
    dots:false,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:4
        },
        1000:{
            items:7
        }
    }
})